apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
  lables: # these are replicaset labels
    app: nginx
    tier: frontend
spec:
  replicas: 3

  selector:
  # these are used to select the pod to create replicas
    matchLables:
      app: nginx
      tier: frontend
  templete:
    # this is pod definition
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl


